### ISSUE TITLE
SocketException Error

### ISSUE THREAD

**Issue by TAMILSELVAN943** [itfat/Traceroute-App#1]
When i entered ip address socket exception error occured.ScreenShot Attached`.If i put my local ip address also this error occured..
![1657620221591](https://user-images.githubusercontent.com/59245291/178466185-af21803d-f2f7-475c-9e99-b5671539f9cf.JPEG)

**Comment by itfat** [comment]
Hi,
Try changing the IP address and port in ```trace.py``` file line ``` app.run(host='192.168.100.9', port=7001,debug =True)``` with your own IP and port.
